server:
  port: 8080

spring:
  application:
    name: ms-rutaexpress-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_JWT_ISSUER_URI:https://login.microsoftonline.com/common/v2.0}
          jwk-set-uri: ${AZURE_JWK_SET_URI:https://login.microsoftonline.com/common/discovery/v2.0/keys}

security:
  azure:
    # Habilitar en entornos donde se valide el JWT real emitido por Azure AD (EC2 / Staging / Prod)
    enabled: ${SECURITY_AZURE_ENABLED:false}

services:
  shipments:
    url: ${SHIPMENTS_SERVICE_URL:http://localhost:8081}
  catalog:
    url: ${CATALOG_SERVICE_URL:http://localhost:8082}
  audit:
    url: ${AUDIT_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html