server:
  port: 8080

spring:
  application:
    name: ms-rutaexpress-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:${AZURE_JWT_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_AkiImfjh5}}
          jwk-set-uri: ${COGNITO_JWK_SET_URI:${AZURE_JWK_SET_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_AkiImfjh5/.well-known/jwks.json}}

security:
  azure:
    enabled: ${SECURITY_AZURE_ENABLED:${SECURITY_COGNITO_ENABLED:false}}

services:
  shipments:
    url: ${SHIPMENTS_SERVICE_URL:http://127.0.0.1:8081}
  catalog:
    url: ${CATALOG_SERVICE_URL:http://127.0.0.1:8082}
  audit:
    url: ${AUDIT_SERVICE_URL:http://127.0.0.1:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html